import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import SearchFilters from "./components/navbar/searchfilters";
import Modal from "./components/modals/modal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Django Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <div className="pt-32">
        {children}
        </div>
        <Modal/>
        </body>
    </html>
  );
}
